version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          pwd
          ls -l
          MINORTAG=0.1
          IMAGE=dexels/navajo.example.test
          BASETAG=${MINORTAG}.${CIRCLE_BUILD_NUM}
          echo "Tagging for: ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}"
          docker build . -t ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM} -t ${IMAGE}:latest
          docker push ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}
          docker push ${IMAGE}:latest