version: 2.1
jobs:
  build:
    docker:
    - image: cimg/base:latest
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASS
    steps:
    - checkout
      # See https://circleci.com/docs/2.0/building-docker-images/
    - setup_remote_docker:
        version: 19.03.13

    - run:
        name: Log in with docker registries
        command: |
          docker --version
          echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

    - run:
        name: Build and push `enterprise-integration-test-script` docker image
        command: |
          pwd
          ls -l
          MINORTAG=0.1
          IMAGE=dexels/enterprise-integration-test-script
          BASETAG=${MINORTAG}.${CIRCLE_BUILD_NUM}
          echo "Tagging for: ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}"
          docker build . -t ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM} -t ${IMAGE}:latest
          docker push ${IMAGE}:${MINORTAG}.${CIRCLE_BUILD_NUM}
          docker push ${IMAGE}:latest

workflows:
  version: 2
  build:
    jobs:
    - build:
        context:
        - dexels_docker_hub
        filters:
          branches:
            only:
              - master
